### ISSUE TITLE
No such file or directory error when creating js file

### ISSUE THREAD

**Issue by ghost** [winton/smart_asset#13]
I'm getting this every time I run smart_asset. It's been this way for about 3 months now and I figured I'd create an issue:

```
$ bundle exec smart_asset

Creating /Users/benjohnson/Dropbox/Code/Ruby/conciergeliveapp.com/public/javascripts/packaged/cad42b92_all.js...
/Users/benjohnson/.rvm/gems/ruby-1.9.3-p0/gems/smart_asset-0.5.9/lib/smart_asset.rb:95:in ``': No such file or directory - uglifyjs --output /Users/benjohnson/Dropbox/Code/Ruby/conciergeliveapp.com/public/javascripts/packaged/cad42b92_all.js -nc /Users/benjohnson/Dropbox/Code/Ruby/conciergeliveapp.com/public/javascripts/packaged/tmp.js (Errno::ENOENT)
    from /Users/benjohnson/.rvm/gems/ruby-1.9.3-p0/gems/smart_asset-0.5.9/lib/smart_asset.rb:95:in `block in compress'
    from /Users/benjohnson/.rvm/gems/ruby-1.9.3-p0/gems/smart_asset-0.5.9/lib/smart_asset.rb:33:in `each'
    from /Users/benjohnson/.rvm/gems/ruby-1.9.3-p0/gems/smart_asset-0.5.9/lib/smart_asset.rb:33:in `compress'
    from /Users/benjohnson/.rvm/gems/ruby-1.9.3-p0/gems/smart_asset-0.5.9/lib/smart_asset.rb:20:in `binary'
    from /Users/benjohnson/.rvm/gems/ruby-1.9.3-p0/gems/smart_asset-0.5.9/bin/smart_asset:5:in `<top (required)>'
    from /Users/benjohnson/.rvm/gems/ruby-1.9.3-p0/bin/smart_asset:19:in `load'
    from /Users/benjohnson/.rvm/gems/ruby-1.9.3-p0/bin/smart_asset:19:in `<main>'
```

**Comment by binarylogic** [comment]
Also, it leaves the tmp.js file in the directory. I have to manually rename the file and delete the old one. Any ideas?
